osx_image: xcode8.3
dist: trusty
sudo: false
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang

cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"

addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - libsecret-1-dev
    - icnsutils

before_install:
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.5.5/git-lfs-$([
  "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.5.5.tar.gz
  | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"

install:
- nvm install 7
- yarn install --network-concurrency 1
- yarn run install-app-deps

script:
- yarn dist:travis

branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"

env:
  global:
    secure: P4NEqGDdhOvUS5dYTleigNANJtHjanVpA4iH0+OCV7cEPWrX9Vdr7Tfn+FrsWrTO6EZKlfNo8TfNDuS/d2DdUJiYHGHr+AoqxCNntkKrBwXtxYU6lyf36nQaqf7scJD9onQOX0y0siDtL657qOexX08TWX26Kgcdgqm4bIVq+9kZu6CG1XseKeMsuRB3da6sx5JYROY9Zec1gV7uB6uVPo04VdNrTrMwF0MQZs5Wep1weWXR6vq9kd27wXBghp05EF2MqN1ozXPECKvmxnKUW//mWkp3jSBDHHHd8mS9Utk+6wA9/kcelG+9GXacZILfW8QpLmKkTlaRO0ONXX1KDdhNFpzf22olgTvAVn02lhXd03u00VUkfHWtPfUOIGq6F8paLrVnl0pvpxcmmlUZLNI9ZAaKqOnhMdSHNBgFsMX8bml//m5AvfkvFe3wNlwCljbX7ZzRwXdnZ/TjHS0aPi2wUyd15S+LQ19WlSA9yK4hJvdqdvCGk/Ok6vjfDGKSmsTCpDCg6OxNTkfXRJqjcea5e+MMmqzvKRJROHQiKKdZ6vsN9eINigS2e1AiyZC5bLjnIGET5Lm+Esl1zDm4FFkCHzZR78leb2THb4elYBv9C2ENVNMHWSMN8I0dSmc2ugVDsNCzUTrWts4Zc8gS/55YoA/hBWLh6r0sXDytSVQ=
